version: 1.0.{build}
configuration: Release
before_build:
- ps: >-
    (new-object net.webclient).DownloadFile('https://download.microsoft.com/download/1/4/1/141760B3-805B-4583-B17C-8C5BC5A876AB/Installers/dotnet-dev-win-x64.1.0.0-preview2-1-003177.exe','core.exe')

    core.exe /install /quiet /norestart

    dotnet restore
build:
  verbosity: minimal
  
after_build:
- dotnet publish C:\projects\myserver\src\Web\MyServer.Web\project.json -o C:\projects\myserver\AppOutput\DeployTest --configuration Release

test: off

artifacts:
- path: AppOutput\DeployTest
  name: DeployTest
  type: WebDeployPackage
  
deploy:
- provider: WebDeploy
  server: atanas.it
  website: MyServer
  username: Administrator
  password: 
    secure: rE55/DZDA+/y1TX0DnrRSQ==
  ntlm: true
  do_not_use_checksum: true
  aspnet_core: true
  aspnet_core_force_restart: true
  artifact: DeployTest
  app_offline: true
  skip_files: web.config
  
- provider: WebDeploy
  server: atanas.it
  website: MyServerDebug
  username: Administrator
  password: 
    secure: rE55/DZDA+/y1TX0DnrRSQ==
  ntlm: true
  do_not_use_checksum: true
  aspnet_core: true
  aspnet_core_force_restart: true
  artifact: DeployTest
  app_offline: true
  skip_files: web.config