image: Visual Studio 2017 RC

version: 1.0.{build}

configuration: Release

before_build:

- set PATH=C:\Program Files (x86)\MSBuild\15.0\Bin;%PATH%
- nuget restore C:\projects\myserver\MyServer.sln -MSBuildVersion 15.1.458.808

build:
  verbosity: minimal
  
after_build:
- dotnet publish -o C:\projects\myserver\AppOutput\DeployTest --configuration Release

test: off

artifacts:
- path: AppOutput\DeployTest
  name: DeployTest
  type: WebDeployPackage
  
deploy:
- provider: WebDeploy
  server: atanas.it
  website: MyServer
  username: Administrator
  password: 
    secure: rE55/DZDA+/y1TX0DnrRSQ==
  ntlm: true
  do_not_use_checksum: true
  aspnet_core: true
  aspnet_core_force_restart: true
  artifact: DeployTest
  app_offline: true
  skip_files: web.config
  
- provider: WebDeploy
  server: atanas.it
  website: MyServerDebug
  username: Administrator
  password: 
    secure: rE55/DZDA+/y1TX0DnrRSQ==
  ntlm: true
  do_not_use_checksum: true
  aspnet_core: true
  aspnet_core_force_restart: true
  artifact: DeployTest
  app_offline: true
  skip_files: web.config
