image: Visual Studio 2017

version: 2.0.{build}

configuration: Release

before_build:
- NuGet Sources Add -Name "telerik.com" -Source "https://nuget.telerik.com/nuget" -UserName "%nuget_user%" -Password "%nuget_pass%"
- dotnet restore

build:
  verbosity: minimal

  
