version: 1.0.{build}
configuration: Release
before_build:
- ps: >-
    (new-object net.webclient).DownloadFile('https://download.microsoft.com/download/0/A/3/0A372822-205D-4A86-BFA7-084D2CBE9EDF/DotNetCore.1.0.1-SDK.1.0.0.Preview2-003133-x64.exe','core.exe')

    core.exe /install /quiet /norestart

    dotnet restore
build:
  verbosity: minimal
  
after_build:
- dotnet publish src/Web/MyServer.Web/project.json
- dir src/Web/MyServer.Web/bin/Debug/netcoreapp1.0/publish
- type src/Web/MyServer.Web/bin/Debug/netcoreapp1.0/publish/web.config
- '"C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" -source:IisApp=''%appveyor_build_folder%/src/Web/MyServer.Web/bin/Debug/netcoreapp1.0/publish'' -dest:IisApp=''MyServer'',ComputerName=''http://atanas.it/msdeploy.axd'',UserName=''$avg123'',Password=''Godcheto1'',IncludeAcls=''False'',AuthType=''Basic'' -verb:sync -enableLink:contentLibExtension  -enableRule:DoNotDeleteRule -retryAttempts:2'