version: 1.0.{build}
configuration: Release
before_build:
- ps: >-
    (new-object net.webclient).DownloadFile('https://download.microsoft.com/download/0/A/3/0A372822-205D-4A86-BFA7-084D2CBE9EDF/DotNetCore.1.0.1-SDK.1.0.0.Preview2-003133-x64.exe','core.exe')

    core.exe /install /quiet /norestart

    dotnet restore
build:
  verbosity: minimal
  
after_build:
- dotnet publish-iis src/Web/MyServer.Web/project.json -o AppOutput\DeployTest --configuration Release
# - dotnet publish-iis src/Web/MyServer.Web/project.json --publish-folder AppOutput\DeployTest --framework %publish:FullTargetFramework%
test: off

artifacts:
- path: AppOutput\DeployTest
  name: DeployTest
  type: WebDeployPackage
  
deploy:
- provider: WebDeploy
  server: atanas.it
  website: MyServer
  username: Administrator
  password: 
    secure: rE55/DZDA+/y1TX0DnrRSQ==
  ntlm: true
  do_not_use_checksum: true
  aspnet_core: true
#  aspnet5: true
  aspnet_core_force_restart: true
  artifact: DeployTest
  app_offline: true