//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyServer.Common.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Common() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyServer.Common.Resources.Common", typeof(Common).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Private.
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Public.
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Registrated.
        /// </summary>
        public static string Registrated {
            get {
                return ResourceManager.GetString("Registrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ^ Date added.
        /// </summary>
        public static string SortDateAddedAsc {
            get {
                return ResourceManager.GetString("SortDateAddedAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to v Date added.
        /// </summary>
        public static string SortDateAddedDesc {
            get {
                return ResourceManager.GetString("SortDateAddedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ^ Image count.
        /// </summary>
        public static string SortImagesCountAsc {
            get {
                return ResourceManager.GetString("SortImagesCountAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to v Image count.
        /// </summary>
        public static string SortImagesCountDesc {
            get {
                return ResourceManager.GetString("SortImagesCountDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ^ Date images.
        /// </summary>
        public static string SortImagesDateAsc {
            get {
                return ResourceManager.GetString("SortImagesDateAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to v Date images.
        /// </summary>
        public static string SortImagesDateDesc {
            get {
                return ResourceManager.GetString("SortImagesDateDesc", resourceCulture);
            }
        }
    }
}
